services:

  banking-mysql:
    image: mysql:8.4
    container_name: banking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banking-network

  config-server:
    image: config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-u",
          "config-admin:root",
          "http://localhost:8888/actuator/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - banking-network

  eureka-service:
    image: eureka-service:latest
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - banking-network

  auth-service:
    image: auth-service:1.0
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: banking-mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      banking-mysql:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - banking-network

  account-service:
    image: account-service:1.0
    container_name: account-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: banking-mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      banking-mysql:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - banking-network

  transaction-service:
    image: transaction-service:1.0
    container_name: transaction-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: banking-mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      banking-mysql:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - banking-network

  message-service:
    image: message-service:1.0
    container_name: message-service
    ports:
      - "8084:8084"
    environment:
      DB_HOST: banking-mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

      EUREKA_URL: ${EUREKA_URL}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      banking-mysql:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - banking-network

  api-gateway:
    image: api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}

      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      config-server:
        condition: service_healthy
      eureka-service:
        condition: service_started
      auth-service:
        condition: service_started
      account-service:
        condition: service_started
      transaction-service:
        condition: service_started
      message-service:
        condition: service_started
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  mysql_data: