spring:
  application:
    name: transaction-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:config-admin}
      password: ${CONFIG_SERVER_PASSWORD:root}