server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:config-admin}
      password: ${CONFIG_SERVER_PASSWORD:root}

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**



eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"