server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

  security:
    user:
      name: config-admin
      password: config@123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/