server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config-admin}
      password: ${CONFIG_SERVER_PASSWORD:root}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangayyeshi/bank-config-repo
          default-label: main
          clone-on-start: true
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics